services:
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: GatewayService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  planservice:
    image: ${DOCKER_REGISTRY-}planservice
    build:
      context: PlanService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: UserService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  examservice:
    image: ${DOCKER_REGISTRY-}examservice
    build:
      context: ExamService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"

